<?php
/*
 * e107 website system
 *
 * Copyright (C) 2008-2016 e107 Inc (e107.org)
 * Released under the terms and conditions of the
 * GNU General Public License (http://www.gnu.org/licenses/gpl.txt)
 *
 * e107 configuration file
 *
 * This file has been generated by the installation script on Mon, 25 Apr 2016 18:50:23 +0000.
 */

$mySQLserver    = 'localhost';
$mySQLuser      = 'root';
$mySQLpassword  = 'root';
$mySQLdefaultdb = 'e107';
$mySQLprefix    = 'e107_';
$mySQLcharset   = 'utf8';

$ADMIN_DIRECTORY     = 'e107_admin/';
$FILES_DIRECTORY     = 'e107_files/';
$IMAGES_DIRECTORY    = 'e107_images/';
$THEMES_DIRECTORY    = 'e107_themes/';
$PLUGINS_DIRECTORY   = 'e107_plugins/';
$HANDLERS_DIRECTORY  = 'e107_handlers/';
$LANGUAGES_DIRECTORY = 'e107_languages/';
$HELP_DIRECTORY      = 'e107_docs/help/';
$MEDIA_DIRECTORY	  = 'e107_media/';
$SYSTEM_DIRECTORY    = 'e107_system/';

